name: LapisPortalsPlus
main: com.toasthax.lapisportalsplus.LapisPortalsPlus
version: 1.3.0
api-version: "1.21"
authors: ["Philip Cartier"]
permissions:
  lapisportalsplus.use:
    default: true
  lapisportalsplus.create:
    default: op
  lapisportalsplus.admin:
    default: op
commands:
  lpp:
    description: LapisPortalsPlus admin command
    permission: lapisportalsplus.admin
    usage: "/lpp debug [on|off]"
